In [2]:
import pandas
from Funcations import *

In [18]:
from tradingview_ta import *
import time

symbol = TA_Handler(
    symbol='BNBUSDT',
    screener='crypto',
    exchange='binance',#binance
    interval= Interval.INTERVAL_15_MINUTES
)

print(symbol.get_analysis().indicators['RSI'])

In [ ]:
from yfinance import *

In [50]:
import ta
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

# دریافت داده تاریخی از Yahoo Finance
# symbol = "BTC-USD"
symbol = "GOLD"
data = yf.download(symbol, start="2024-01-15", end="2024-01-21",interval="1M")

# افزودن شاخص‌های تحلیل تکنیکال
data = ta.add_all_ta_features(data, open="Open", high="High", low="Low", close="Close", volume="Volume")
data2 = data.copy()

[*********************100%%**********************]  1 of 1 completed

c:\Users\mOsTaFa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ta\trend.py:1030: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  self._psar[i] = high2

In [51]:
data2

,Open,High,Low,Close,Adj Close,Volume,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
Datetime,,,,,,,,,,,,,,,,,,,,,
2024-01-16 09:30:00,17.280001,17.309999,17.230000,17.260000,17.260000,310779,-77689.192833,310779,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
2024-01-16 09:31:00,17.250000,17.299999,17.235001,17.235001,17.235001,41127,-118816.192833,269652,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.144841,-0.144946,-0.144841
2024-01-16 09:32:00,17.230000,17.230000,17.200001,17.219999,17.219999,20288,-112054.386119,249364,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.087040,-0.087078,-0.231755
2024-01-16 09:33:00,17.200001,17.250000,17.150000,17.160000,17.160000,447414,-469983.879377,-198050,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.348429,-0.349037,-0.579376
2024-01-16 09:34:00,17.160000,17.160000,17.084999,17.100000,17.100000,71974,-513166.082927,-270024,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.349647,-0.350260,-0.926998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-01-19 15:55:00,15.600000,15.610000,15.599000,15.610000,15.610000,88804,-454964.521385,4534803,0.131673,274.311216,...,0.008560,-0.009941,0.018501,20.825641,20.205798,0.619842,15.579241,0.064098,0.064077,-9.559679
2024-01-19 15:56:00,15.610000,15.610000,15.605000,15.605000,15.605000,48424,-503388.521385,4486379,0.089439,200.534536,...,0.012700,-0.005413,0.018113,16.237558,19.412150,-3.174592,15.581053,-0.032031,-0.032037,-9.588648
2024-01-19 15:57:00,15.610000,15.615000,15.600100,15.615000,15.615000,81136,-422252.521385,4567515,0.135625,287.797970,...,0.020912,-0.000148,0.021060,16.138048,18.757330,-2.619281,15.585591,0.064083,0.064063,-9.530709
2024-01-19 15:58:00,15.615000,15.620000,15.610000,15.610000,15.610000,109537,-531789.521385,4457978,0.052964,168.441469,...,0.024550,0.004792,0.019758,18.797145,18.765293,0.031852,15.587974,-0.032021,-0.032026,-9.559679
2024-01-19 15:59:00,15.615000,15.620000,15.600000,15.600000,15.600000,364979,-896768.521385,4092999,-0.166267,-376.982379,...,0.022007,0.008235,0.013772,39.267966,22.865828,16.402138,15.589148,-0.064057,-0.064077,-9.617612

In [ ]:
import yfinance as yf
from datetime import datetime

# CREATE TICKER INSTANCE FOR AMAZON
amzn = yf.Ticker("AMZN")

# GET TODAYS DATE AND CONVERT IT TO A STRING WITH YYYY-MM-DD FORMAT (YFINANCE EXPECTS THAT FORMAT)
end_date = datetime.now().strftime('%Y-%m-%d')
amzn_hist = amzn.history(start='2023-10-01',end=end_date)
print(amzn_hist)

In [44]:
amzn_hist2 = amzn_hist.copy()

In [52]:
data2.reset_index(inplace=True)
data2['Datetime']

0      2024-01-16 09:30:00
1      2024-01-16 09:31:00
2      2024-01-16 09:32:00
3      2024-01-16 09:33:00
4      2024-01-16 09:34:00
               ...
1555   2024-01-19 15:55:00
1556   2024-01-19 15:56:00
1557   2024-01-19 15:57:00
1558   2024-01-19 15:58:00
1559   2024-01-19 15:59:00
Name: Datetime, Length: 1560, dtype: datetime64[ns]

In [62]:
amzn_hist2.drop(['Dividends','Stock Splits'],inplace=True,axis=1)
amzn_hist2.reset_index(inplace=True)
amzn_hist2.rename(columns={'Date':'Datetime'},inplace = True)
amzn_hist2['Datetime'] = amzn_hist2['Datetime'].astype(str)
amzn_hist2['Datetime'] = amzn_hist2['Datetime'].apply(lambda x: x.rsplit('-', 1)[0]).tolist()

In [82]:
#  2024-01-16 09:30:00  -> 2024-01-19 15:59:00
path = "./PriceData/STOCKS/AAPL_1560_1M.csv" #APPLE 
# path = "./PriceData/STOCKS/META_1560_1M.csv" #META
# path = ...
data2 = pd.read_csv(path)

In [83]:
#  2024-01-16 09:30:00  -> 2024-01-19 15:59:00
path = "./PriceData/STOCKS/AAPL_1560_1M.csv" #APPLE 
# path = "./PriceData/STOCKS/META_1560_1M.csv" #META
# path = ...
data2 = pd.read_csv(path)

dataF = data2.copy()
dataF = pd.DataFrame(dataF,columns=['Datetime','Open','High','Low','Close','Volume'])
# dataF.to_csv(path)

dataF = signal_generator(dataF)
dataF = calculate_signals(dataF)

# dataF
result2 = BackTest(dataF,'Strategy 2')

print(result2.ShowResult())

Best Winrate : 66.66666666666666
Best Waiting time : 7 minutes
Good Signal : 28
Bad Signal : 13

In [ ]:
import os

In [14]:
import ta
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from Funcations import *
# دریافت داده تاریخی از Yahoo Finance
# symbol = "BTC-USD"
symbol = "SI=F" 
data = yf.download(symbol, start="2024-01-15", end="2024-01-21" , interval='1m')

# افزودن شاخص‌های تحلیل تکنیکال
data = ta.add_all_ta_features(data, open="Open", high="High", low="Low", close="Close", volume="Volume")
data.reset_index(inplace=True)
data2 = data.copy()

# # FUTURES
#  # 2024-01-16 09:30:00  -> 2024-01-19 15:59:00

# # STOCKS
# #  2024-01-16 09:30:00  -> 2024-01-19 15:59:00
# path = "./PriceData/STOCKS/AAPL_1560_1M.csv" #APPLE 
# path = "./PriceData/STOCKS/META_1560_1M.csv" #META

# # Crypto
# path = "./PriceData/CRYPTO/BTCUSDT_1500_5M.csv"
# path = "./PriceData/CRYPTO/BTCUSDT_1500_15M.csv"
# path = "./PriceData/CRYPTO/ETHUSD_1500_1d.csv"
# path = "./PriceData/CRYPTO/DOGEUSD_1000_15M.csv"


data2.to_csv("./PriceData/SILVER.csv")

[*********************100%%**********************]  1 of 1 completed

c:\Users\mOsTaFa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ta\trend.py:1030: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  self._psar[i] = high2

In [16]:
data2 = data.copy()

In [17]:
data2

,Datetime,Open,High,Low,Close,Adj Close,Volume,volume_adi,volume_obv,volume_cmf,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
0,2024-01-15 00:01:00-05:00,23.415001,23.415001,23.410000,23.415001,23.415001,0,0.000000,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
1,2024-01-15 00:02:00-05:00,23.415001,23.415001,23.415001,23.415001,23.415001,4,0.000000,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
2,2024-01-15 00:05:00-05:00,23.420000,23.420000,23.420000,23.420000,23.420000,2,0.000000,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021350,0.021348,0.021350
3,2024-01-15 00:06:00-05:00,23.420000,23.420000,23.415001,23.415001,23.415001,4,-4.000000,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.021346,-0.021348,0.000000
4,2024-01-15 00:07:00-05:00,23.420000,23.420000,23.420000,23.420000,23.420000,5,-4.000000,7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021350,0.021348,0.021350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5993,2024-01-19 16:55:00-05:00,22.740000,22.745001,22.740000,22.745001,22.745001,19,-4330.390972,25603,0.302326,...,0.016889,0.016085,0.000804,35.628749,23.123136,12.505613,22.739343,0.000000,0.000000,-2.861414
5994,2024-01-19 16:56:00-05:00,22.745001,22.750000,22.745001,22.750000,22.750000,20,-4310.390972,25623,0.333333,...,0.018742,0.016616,0.002126,29.952447,24.488999,5.463449,22.739836,0.021979,0.021977,-2.840064
5995,2024-01-19 16:57:00-05:00,22.750000,22.750000,22.750000,22.750000,22.750000,6,-4310.390972,25629,0.371859,...,0.019981,0.017289,0.002692,20.776958,23.746591,-2.969632,22.740067,0.000000,0.000000,-2.840064
5996,2024-01-19 16:58:00-05:00,22.750000,22.754999,22.750000,22.750000,22.750000,28,-4338.390972,25657,0.290780,...,0.020724,0.017976,0.002747,20.369740,23.071220,-2.701481,22.740765,0.000000,0.000000,-2.840064
5997,2024-01-19 16:59:00-05:00,22.754999,22.754999,22.711000,22.750000,22.750000,15,-4326.799590,25672,0.252688,...,0.021069,0.018595,0.002474,15.480419,21.553060,-6.072641,22.744870,0.000000,0.000000,-2.840064

In [12]:
# path = './PriceData/SILVER.csv'

# data2 = pd.read_csv(path)

# data2.drop(['Unnamed: 0'],axis=1,inplace=True)
# data2.rename(columns = {'Date':"Datetime"},inplace=True)

# data2 = pd.DataFrame(data2,columns=['Datetime','Open','High','Low','Close','Volume'])

data2

     Datetime       Open       High        Low      Close  Volume
0     2024-01  23.415001  23.415001  23.410000  23.415001       0
1     2024-01  23.415001  23.415001  23.415001  23.415001       4
2     2024-01  23.420000  23.420000  23.420000  23.420000       2
3     2024-01  23.420000  23.420000  23.415001  23.415001       4
4     2024-01  23.420000  23.420000  23.420000  23.420000       5
...       ...        ...        ...        ...        ...     ...
5993  2024-01  22.740000  22.745001  22.740000  22.745001      19
5994  2024-01  22.745001  22.750000  22.745001  22.750000      20
5995  2024-01  22.750000  22.750000  22.750000  22.750000       6
5996  2024-01  22.750000  22.754999  22.750000  22.750000      28
5997  2024-01  22.754999  22.754999  22.711000  22.750000      15

[5998 rows x 6 columns]

In [18]:
amzn_hist2 = data2
# amzn_hist2.drop(['Dividends','Stock Splits'],inplace=True,axis=1)
# amzn_hist2.reset_index(inplace=True)
# amzn_hist2.rename(columns={'Date':'Datetime'},inplace = True)
amzn_hist2['Datetime'] = amzn_hist2['Datetime'].astype(str)
amzn_hist2['Datetime'] = amzn_hist2['Datetime'].apply(lambda x: x.rsplit('-', 1)[0]).tolist()

In [25]:
amzn_hist2

,Datetime,Open,High,Low,Close,Adj Close,Volume,volume_adi,volume_obv,volume_cmf,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
0,2024-01-15 00:01:00,23.415001,23.415001,23.410000,23.415001,23.415001,0,0.000000,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
1,2024-01-15 00:02:00,23.415001,23.415001,23.415001,23.415001,23.415001,4,0.000000,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
2,2024-01-15 00:05:00,23.420000,23.420000,23.420000,23.420000,23.420000,2,0.000000,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021350,0.021348,0.021350
3,2024-01-15 00:06:00,23.420000,23.420000,23.415001,23.415001,23.415001,4,-4.000000,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.021346,-0.021348,0.000000
4,2024-01-15 00:07:00,23.420000,23.420000,23.420000,23.420000,23.420000,5,-4.000000,7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021350,0.021348,0.021350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5993,2024-01-19 16:55:00,22.740000,22.745001,22.740000,22.745001,22.745001,19,-4330.390972,25603,0.302326,...,0.016889,0.016085,0.000804,35.628749,23.123136,12.505613,22.739343,0.000000,0.000000,-2.861414
5994,2024-01-19 16:56:00,22.745001,22.750000,22.745001,22.750000,22.750000,20,-4310.390972,25623,0.333333,...,0.018742,0.016616,0.002126,29.952447,24.488999,5.463449,22.739836,0.021979,0.021977,-2.840064
5995,2024-01-19 16:57:00,22.750000,22.750000,22.750000,22.750000,22.750000,6,-4310.390972,25629,0.371859,...,0.019981,0.017289,0.002692,20.776958,23.746591,-2.969632,22.740067,0.000000,0.000000,-2.840064
5996,2024-01-19 16:58:00,22.750000,22.754999,22.750000,22.750000,22.750000,28,-4338.390972,25657,0.290780,...,0.020724,0.017976,0.002747,20.369740,23.071220,-2.701481,22.740765,0.000000,0.000000,-2.840064
5997,2024-01-19 16:59:00,22.754999,22.754999,22.711000,22.750000,22.750000,15,-4326.799590,25672,0.252688,...,0.021069,0.018595,0.002474,15.480419,21.553060,-6.072641,22.744870,0.000000,0.000000,-2.840064

In [21]:
path = './PriceData/SILVER.csv'
amzn_hist2.to_csv(path)

In [24]:
data2 = pd.read_csv(path)
data2

,Unnamed: 0,Datetime,Open,High,Low,Close,Adj Close,Volume,volume_adi,volume_obv,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
0,0,2024-01-15 00:01:00,23.415001,23.415001,23.410000,23.415001,23.415001,0,0.000000,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
1,1,2024-01-15 00:02:00,23.415001,23.415001,23.415001,23.415001,23.415001,4,0.000000,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
2,2,2024-01-15 00:05:00,23.420000,23.420000,23.420000,23.420000,23.420000,2,0.000000,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021350,0.021348,0.021350
3,3,2024-01-15 00:06:00,23.420000,23.420000,23.415001,23.415001,23.415001,4,-4.000000,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.021346,-0.021348,0.000000
4,4,2024-01-15 00:07:00,23.420000,23.420000,23.420000,23.420000,23.420000,5,-4.000000,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.021350,0.021348,0.021350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5993,5993,2024-01-19 16:55:00,22.740000,22.745001,22.740000,22.745001,22.745001,19,-4330.390972,25603,...,0.016889,0.016085,0.000804,35.628749,23.123136,12.505613,22.739343,0.000000,0.000000,-2.861414
5994,5994,2024-01-19 16:56:00,22.745001,22.750000,22.745001,22.750000,22.750000,20,-4310.390972,25623,...,0.018742,0.016616,0.002126,29.952447,24.488999,5.463449,22.739836,0.021979,0.021977,-2.840064
5995,5995,2024-01-19 16:57:00,22.750000,22.750000,22.750000,22.750000,22.750000,6,-4310.390972,25629,...,0.019981,0.017289,0.002692,20.776958,23.746591,-2.969632,22.740067,0.000000,0.000000,-2.840064
5996,5996,2024-01-19 16:58:00,22.750000,22.754999,22.750000,22.750000,22.750000,28,-4338.390972,25657,...,0.020724,0.017976,0.002747,20.369740,23.071220,-2.701481,22.740765,0.000000,0.000000,-2.840064
5997,5997,2024-01-19 16:59:00,22.754999,22.754999,22.711000,22.750000,22.750000,15,-4326.799590,25672,...,0.021069,0.018595,0.002474,15.480419,21.553060,-6.072641,22.744870,0.000000,0.000000,-2.840064

In [127]:



dataF = amzn_hist2.copy()
dataF = pd.DataFrame(dataF,columns=['Datetime','Open','High','Low','Close','Volume'])
# dataF.to_csv(path)

dataF = signal_generator(dataF)
dataF = calculate_signals(dataF)

result2 = BackTest(dataF,'Strategy 2')

print(result2.ShowResult())

Best Winrate : 55.55555555555556
Best Waiting time : 2 minutes
Good Signal : 20
Bad Signal : 11