### 1 - Import test data

In [4]:
import pandas as pd
import ccxt
import time
import ta
import MarketSimulation as MS
# Set up the trading parameters
symbol = 'BTC/USDT'  # Use the trading pair you are interested in
timeframe = '1d' #'15m'    # Use the desired timeframe
volume = 0.5        # Volume of the trade

exchange = ccxt.kucoin() 

# ohlcv = exchange.fetch_ohlcv(symbol, timeframe, limit=100)
# df = pd.DataFrame(ohlcv, columns=['Datetime', 'Open', 'High', 'Low', 'Close', 'Volume'])
# df['Datetime'] = pd.to_datetime(df['Datetime'], unit='ms')

# df = MS.ReceivingInformation_all()

In [5]:
df['RSI'] = ta.momentum.RSIIndicator(df['Close']).rsi()
df['MACD'] = ta.trend.MACD(df['Close']).macd()

In [8]:
# from tradingview_ta import *
# import time

# symbol = TA_Handler(
#     symbol='BNBUSDT',
#     screener='crypto',
#     exchange='kucoin',#binance
#     interval= Interval.INTERVAL_15_MINUTES
# )

# print(symbol.get_analysis().indicators['RSI'])

45.76835829

In [6]:
dataF = df
dataF.set_index('Datetime',inplace=True)
dataF

,Open,High,Low,Close,Volume,RSI,MACD
Datetime,,,,,,,
2023-12-25 00:00:00,42994.8,43095.0,42946.0,43015.5,30.419231,NaN,NaN
2023-12-25 00:15:00,43010.4,43019.7,42820.3,42918.3,59.462150,NaN,NaN
2023-12-25 00:30:00,42913.7,42931.5,42736.4,42755.5,51.289633,NaN,NaN
2023-12-25 00:45:00,42759.7,42922.0,42757.7,42915.9,22.652463,NaN,NaN
2023-12-25 01:00:00,42916.0,43084.3,42913.7,43027.2,32.569299,NaN,NaN
...,...,...,...,...,...,...,...
2024-01-09 13:45:00,46605.6,47071.6,46595.0,46837.5,113.396134,56.261713,-8.340577
2024-01-09 14:00:00,46837.5,46998.0,46757.7,46830.7,96.834040,56.040119,9.647841
2024-01-09 14:15:00,46832.6,46837.3,46656.5,46742.7,88.745065,53.124073,16.611441
2024-01-09 14:30:00,46743.8,46764.9,46584.8,46592.3,57.004972,48.480891,9.880228
2024-01-09 14:45:00,46592.4,46762.0,46546.0,46762.0,35.295839,53.427140,18.031213

In [7]:
dataF

,Open,High,Low,Close,Volume,RSI,MACD
Datetime,,,,,,,
2023-12-25 00:00:00,42994.8,43095.0,42946.0,43015.5,30.419231,NaN,NaN
2023-12-25 00:15:00,43010.4,43019.7,42820.3,42918.3,59.462150,NaN,NaN
2023-12-25 00:30:00,42913.7,42931.5,42736.4,42755.5,51.289633,NaN,NaN
2023-12-25 00:45:00,42759.7,42922.0,42757.7,42915.9,22.652463,NaN,NaN
2023-12-25 01:00:00,42916.0,43084.3,42913.7,43027.2,32.569299,NaN,NaN
...,...,...,...,...,...,...,...
2024-01-09 13:45:00,46605.6,47071.6,46595.0,46837.5,113.396134,56.261713,-8.340577
2024-01-09 14:00:00,46837.5,46998.0,46757.7,46830.7,96.834040,56.040119,9.647841
2024-01-09 14:15:00,46832.6,46837.3,46656.5,46742.7,88.745065,53.124073,16.611441
2024-01-09 14:30:00,46743.8,46764.9,46584.8,46592.3,57.004972,48.480891,9.880228
2024-01-09 14:45:00,46592.4,46762.0,46546.0,46762.0,35.295839,53.427140,18.031213

## DF to CSV
### CSV to DF

In [ ]:
path = "./Data/ETHUSD_1500_1d.csv"

# dataF.to_csv(path)

dataF = pd.read_csv(path)
dataF.set_index("Datetime",inplace=True)
dataF

### 2 - Define your signal function

In [14]:
def signal_generator(df):
    open = df.Open.iloc[-1]
    close = df.Close.iloc[-1]
    previous_open = df.Open.iloc[-2]
    previous_close = df.Close.iloc[-2]
    
    # Bearish Pattern
    if (open>close and 
    previous_open<previous_close and 
    close<previous_open and
    open>=previous_close):
        return 1

    # Bullish Pattern
    elif (open<close and 
        previous_open>previous_close and 
        close>previous_open and
        open<=previous_close):
        return 2
    
    # No clear pattern
    else:
        return 0

BuySignal = [0]
SellSignal = [0]

for i in range(1,len(dataF)):
    df = dataF[i-1:i+1]
    signal = signal_generator(df)
    if signal == 1:
        BuySignal.append(1)
        SellSignal.append(0)
    elif signal == 2:
        SellSignal.append(1)
        BuySignal.append(0)
    else:
        SellSignal.append(0)
        BuySignal.append(0)
#signal_generator(data)
dataF["ST2_Buy_Signal"] = BuySignal
dataF["ST2_Sell_Signal"] = SellSignal

In [11]:
dataF.head()

,Open,High,Low,Close,Volume,RSI,MACD,ST2_Buy_Signal,ST2_Sell_Signal
Datetime,,,,,,,,,
2023-12-25 00:00:00,42994.8,43095.0,42946.0,43015.5,30.419231,NaN,NaN,0,0
2023-12-25 00:15:00,43010.4,43019.7,42820.3,42918.3,59.462150,NaN,NaN,0,0
2023-12-25 00:30:00,42913.7,42931.5,42736.4,42755.5,51.289633,NaN,NaN,0,0
2023-12-25 00:45:00,42759.7,42922.0,42757.7,42915.9,22.652463,NaN,NaN,0,0
2023-12-25 01:00:00,42916.0,43084.3,42913.7,43027.2,32.569299,NaN,NaN,0,0

# Backtest

In [15]:

def BackTest(limit_ft):
    TotalSignal = 0 
    BadSignal , GoodSignal = 0 , 0 
    dataliBUY = dataF["ST2_Buy_Signal"].to_list()
    dataliSELL = dataF["ST2_Sell_Signal"].to_list()

    for i in range(0,len(dataF["Close"])-limit_ft):

        FuturePrice =0
        CurrentPrice = dataF.iloc[i].Close
        FuturePrice=dataF.iloc[i+limit_ft].Close
        # for j in range(1,limit_ft+1):
        #     FuturePrice+=dataF.iloc[i+j].Close
        #     FuturePrice = FuturePrice/limit_ft

        if dataliSELL[i] == 1: #Sell
            # print(dataF.iloc[i].name)
            if FuturePrice < CurrentPrice:
                GoodSignal += 1
            elif FuturePrice > CurrentPrice:
                BadSignal +=1
        elif dataliBUY[i] == 1: #Buy
            if FuturePrice > CurrentPrice:
                GoodSignal += 1
            elif FuturePrice < CurrentPrice:
                BadSignal +=1
    
    print(f"Good Signal : {GoodSignal} \nBad Signal : {BadSignal}")
    
    for i in range(0,len(dataF["Close"])):
        if dataliBUY[i] != 0 or dataliSELL[i] != 0 : 
            TotalSignal+=1   
    return  (GoodSignal/TotalSignal)*100

In [16]:
# print(f"Winrate : { BackTest(5) }" )

best_winrate = 0
for i in range(0,12):
    if best_winrate < BackTest(i):
        best_winrate = BackTest(i)
        best_limit = i
print(f"Best Winrate : {best_winrate} Best_limit : {best_limit}")


# dataF.signal.value_counts()
#dataF.iloc[:, :]

Good Signal : 0
Bad Signal : 0
Good Signal : 148
Bad Signal : 117
Good Signal : 148
Bad Signal : 117
Good Signal : 144
Bad Signal : 121
Good Signal : 145
Bad Signal : 119
Good Signal : 150
Bad Signal : 115
Good Signal : 150
Bad Signal : 115
Good Signal : 142
Bad Signal : 122
Good Signal : 151
Bad Signal : 113
Good Signal : 151
Bad Signal : 113
Good Signal : 150
Bad Signal : 114
Good Signal : 158
Bad Signal : 106
Good Signal : 158
Bad Signal : 106
Good Signal : 152
Bad Signal : 112
Good Signal : 148
Bad Signal : 116
Good Signal : 154
Bad Signal : 110
Best Winrate : 59.62264150943396 Best_limit : 8

### 3 - Connect to the market and execute trades

In [5]:
from apscheduler.schedulers.blocking import BlockingScheduler
from oandapyV20 import API
import oandapyV20.endpoints.orders as orders
from oandapyV20.contrib.requests import MarketOrderRequest
from oanda_candles import Pair, Gran, CandleClient
from oandapyV20.contrib.requests import TakeProfitDetails, StopLossDetails

In [6]:
from config import access_token, accountID
def get_candles(n):
    #access_token='XXXXXXX'#you need token here generated from OANDA account
    client = CandleClient(access_token, real=False)
    collector = client.get_collector(Pair.EUR_USD, Gran.M15)
    candles = collector.grab(n)
    return candles

candles = get_candles(3)
for candle in candles:
    print(float(str(candle.bid.o))>1)

True
True
True

In [12]:
def trading_job():
    candles = get_candles(3)
    dfstream = pd.DataFrame(columns=['Open','Close','High','Low'])
    
    i=0
    for candle in candles:
        dfstream.loc[i, ['Open']] = float(str(candle.bid.o))
        dfstream.loc[i, ['Close']] = float(str(candle.bid.c))
        dfstream.loc[i, ['High']] = float(str(candle.bid.h))
        dfstream.loc[i, ['Low']] = float(str(candle.bid.l))
        i=i+1

    dfstream['Open'] = dfstream['Open'].astype(float)
    dfstream['Close'] = dfstream['Close'].astype(float)
    dfstream['High'] = dfstream['High'].astype(float)
    dfstream['Low'] = dfstream['Low'].astype(float)

    signal = signal_generator(dfstream.iloc[:-1,:])#
    
    # EXECUTING ORDERS
    #accountID = "XXXXXXX" #your account ID here
    client = API(access_token)
         
    SLTPRatio = 2.
    previous_candleR = abs(dfstream['High'].iloc[-2]-dfstream['Low'].iloc[-2])
    
    SLBuy = float(str(candle.bid.o))-previous_candleR
    SLSell = float(str(candle.bid.o))+previous_candleR

    TPBuy = float(str(candle.bid.o))+previous_candleR*SLTPRatio
    TPSell = float(str(candle.bid.o))-previous_candleR*SLTPRatio
    
    print(dfstream.iloc[:-1,:])
    print(TPBuy, "  ", SLBuy, "  ", TPSell, "  ", SLSell)
    signal = 2
    #Sell
    if signal == 1:
        mo = MarketOrderRequest(instrument="EUR_USD", units=-1000, takeProfitOnFill=TakeProfitDetails(price=TPSell).data, stopLossOnFill=StopLossDetails(price=SLSell).data)
        r = orders.OrderCreate(accountID, data=mo.data)
        rv = client.request(r)
        print(rv)
    #Buy
    elif signal == 2:
        mo = MarketOrderRequest(instrument="EUR_USD", units=1000, takeProfitOnFill=TakeProfitDetails(price=TPBuy).data, stopLossOnFill=StopLossDetails(price=SLBuy).data)
        r = orders.OrderCreate(accountID, data=mo.data)
        rv = client.request(r)
        print(rv)

### 4 - Executing orders automatically with a scheduler

In [ ]:
trading_job()

scheduler = BlockingScheduler()
scheduler.add_job(trading_job, 'cron', day_of_week='mon-fri', hour='00-23', minute='1,16,31,46', start_date='2022-01-12 12:00:00', timezone='America/Chicago')
scheduler.start()